name: Reusable Apigee Deploy

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pushed branch
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}
          path: deployed

      - name: Checkout master scripts
        uses: actions/checkout@v6
        with:
          ref: master
          path: master

      - name: Checkout token generator
        uses: actions/checkout@v6
        with:
          ref: feature/get-access-token
          path: get-access-token

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - run: pip install -r ./get-access-token/requirements.txt

      - name: Get OAuth token
        id: token
        run: |
          TOKEN=$(python ./get-access-token/auth2.py)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - run: chmod +x ./master/script.sh

      - name: Run deploy
        run: ./master/script.sh
        env:
          APIGEE_TOKEN: ${{ steps.token.outputs.token }}
